//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.10.17 at 03:33:43 AM EDT 
//


package edu.ncsu.dre.impl.engine.alexa;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchResultComponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchResultComponent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SearchTerms" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EstimatedNumberOfDocuments" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Document" type="{}ResultComponent" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchResultComponent", propOrder = {
    "searchTerms",
    "estimatedNumberOfDocuments",
    "document"
})
public class SearchResultComponent {

    @XmlElement(name = "SearchTerms", required = true)
    protected String searchTerms;
    @XmlElement(name = "EstimatedNumberOfDocuments", required = true)
    protected String estimatedNumberOfDocuments;
    @XmlElement(name = "Document", required = true)
    protected List<ResultComponent> document;

    /**
     * Gets the value of the searchTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchTerms() {
        return searchTerms;
    }

    /**
     * Sets the value of the searchTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchTerms(String value) {
        this.searchTerms = value;
    }

    /**
     * Gets the value of the estimatedNumberOfDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstimatedNumberOfDocuments() {
        return estimatedNumberOfDocuments;
    }

    /**
     * Sets the value of the estimatedNumberOfDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstimatedNumberOfDocuments(String value) {
        this.estimatedNumberOfDocuments = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the document property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResultComponent }
     * 
     * 
     */
    public List<ResultComponent> getDocument() {
        if (document == null) {
            document = new ArrayList<ResultComponent>();
        }
        return this.document;
    }

}
